### PR TITLE
Fixes #42. Add Latest Sliding Cards Carousal/Stack on Home Page

### LINKED ISSUE #42: Add Latest searches cards on Home Page
Add user stats card on home page (right side) for the latest searches. Show user img, username, bio, repo count, followers, PR count, issue count.

Take inspiration from sliding cards on online.codingblocks.com, also make them auto slide in a loop.

Fetch data from latestUsers query. 

This needs to be completed first : https://github.com/hereisnaman/api.gitfa.me/issues/25

### PR DESCRIPTION
**Pull request by kapillamba4**

### CODE REVIEW

**Comment by 0xnmn** [comment]
@kapillamba4 add gif for working ui changes.

**Comment by kapillamba4** [comment]
@hereisnaman I have added the gif, review please:
awesomescreenshot-2018-05-23t14-36-39-650z

I am adding another one for width < 780px

**Comment by kapillamba4** [comment]
@hereisnaman review please
awesome2

**Comment by kapillamba4** [comment]
@hereisnaman review please

**Pull request merged**
